### ISSUE TITLE
Responsiveness stops when switching to another view and switching back

### ISSUE THREAD

**Issue by felix-d** [ttippin84/VBResponsiveTextFieldViewController#3]
Thanks for your awesome class, I began ios development yesterday and you saved my life!

There is an issue though
The textfield is responsive till I switch to another view via a tab controller. Then, when I switch back, it stops being responsive. Do I need to do something? Is that a bug?

Thanks!

Edit: Nevermind, the issue is with Swift version actually. WRONG PLACE!

**Comment by ttippin84** [comment]
Hey,

I haven't really dug into Swift yet, but what I think is causing your issue
is the code that sets up the view controller to observe the keyboard events
happens in the viewDidLoad method and it "unobserves" these events in the
viewWillDisappear method. This was really more of an oversight during the
design of the class - I wasn't expecting people to go back and forth with
this particular view controller. Also, I wouldn't recommend calling
viewDidLoad in your own code to solve the issue, a better solution would be
to move all the code in the viewDidLoad method to the viewWillAppear method
or the viewWillAppear method of your class. Feel free to fork these changes
on github for others who run into this issue!

Take care!

**Comment by felix-d** [comment]
Yeah that's what I did https://github.com/flexdec/VBResponsiveTextFieldViewController
Thanks!
